[package]
name = "std-logger"
version = "0.1.0"
authors = ["Thomas de Zeeuw <thomasdezeeuw@gmail.com>"]
description = """
A logging implementation for the log crate that logs messages to standard
error and requests to standard out.
"""
repository = "https://github.com/Thomasdezeeuw/std-logger"
readme = "README.md"
keywords = ["logging", "log", "standard"]
license = "MIT/Apache-2.0"

[badges]
travis-ci = { repository = "Thomasdezeeuw/std-logger" }
appveyor = { repository = "Thomasdezeeuw/std-logger", service = "github" }

[features]
default = ["timestamp", "log-panic"]
timestamp = ["chrono"]
log-panic = ["log-panics"]

[dependencies]
log = "0.3"
chrono = { version = "0.4", optional = true }
log-panics = { version = "1.2", optional = true, features = ["with-backtrace"] }
